Update xml-check.yml

diff --git a/.github/workflows/xml-check.yml b/.github/workflows/xml-check.yml
--- a/.github/workflows/xml-check.yml
+++ b/.github/workflows/xml-check.yml
@@ -18,8 +18,14 @@ jobs:
       with:
         python-version: '3.x'
 
-    - name: Install lxml
-      run: python -m pip install lxml
-
     - name: Check XML files
-      run: python .github/workflows/xml_check.py
+      run: |
+        python -m pip install lxml
+        python .github/workflows/xml_check.py
+
+    - name: Check script status
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "XML check failed. Exiting with a non-zero code."
+          exit 1
+        fi
